#!/bin/bash
echo $(printf "%o" $(($(printf "%d\n" 0x$(echo $WATER | tr 'water' '01234' | tr -d '\n')) + $(printf "%d\n" 0x$(echo $STIR | tr 'stir.' '01234' | tr -d '\n'))))) | tr '01234567' 'bestchol'
